### ISSUE TITLE
Is base learner (component-wise)simple OLS in `glmboost` for any family

### ISSUE THREAD

**Issue by BruceChen2017** [boost-R/mboost#103]
Just for confirmation.If it is, which part of source code reveales this?By the way, what is the usage of `loss` agrument in `Family` object. Thanks in advance!

**Comment by fabian-s** [comment]
yes, it is OLS (but it can also do a ridge-penalized fit)
this function sets up the design matrix for `bols` learners:
https://github.com/boost-R/mboost/blob/84712fcb27511f45ae6664078dd772d1750c8549/R/bl.R#L92

the `loss`-argument defines the loss function -- as the manual says "an optional loss function with arguments y and f."
y are the responses, f is the additive predictor/model prediction

**Comment by BruceChen2017** [comment]
@fabian-s Thanks. What does "optional" means? If I understand correctly, such  loss function would be used to calculate `AIC`.Such understanding comes after I read this paper [Boosting Algorithms:Regularization,Prediction and Model Fitting](https://arxiv.org/pdf/0804.2752.pdf)

**Comment by fabian-s** [comment]
there's a misunderstanding -- this forum is for reporting bugs or feature requests for mboost, not  for teaching people about boosting. better forums for that kind of question: crossvalidated or any of the subreddits devoted to stats or machine learning. good luck!
