### ISSUE TITLE
Is there a way to illustrate the confidence interval ?

### ISSUE THREAD

**Issue by zhongzhixu** [boost-R/mboost#106]
Hi authors,

Thanks for the great work, impressive.

Can I ask whether there exists a way to visualize the confidence interval ?

Such as the error bar showing in paper http://people.dbmi.columbia.edu/noemie/papers/15kdd.pdf

Thanks,
Julien

**Comment by hofnerb** [comment]
Thank you for your feedback. There are functions to estimate and plot CIs for boosted models. See `?confint.mboost` for details.
