### ISSUE TITLE
Extracts splits from an mboost object

### ISSUE THREAD

**Issue by BerriJ** [boost-R/mboost#107]
Hi there,

I am currently using mboost to fit boosted trees and I would like to take a look at the splits. Is there a way to extract this information from the model object? The information about splitting must be in there somehow, otherwise we would not be able to use predict() on new data. However, the predict method seems really complex.

I made up the following toy model for testing:

```
set.seed(1907) 
x1 <- rnorm(1000) 
x2 <- rnorm(1000) 
x3 <- rnorm(1000) 
x4 <- rnorm(1000) 
x5 <- rnorm(1000) 
x6 <- rnorm(1000) 
mu <- exp(1.5 +1 * x1 +0.5 * x2 -0.5 * x3 -1 * x4) 
sigma <- exp(-0.4 * x3 -0.2 * x4 +0.2 * x5 +0.4 * x6) 
y <- numeric(1000) 
for( i in 1:1000) y[i] <- rnbinom(1, size = sigma[i], mu = mu[i]) 
dat <- data.frame(x1, x2, x3, x4, x5, x6, y) ### linear model with y ~ . for both components: 400 boosting iterations 

formula_ <- list(mu = y ~ btree(x1,x2),
     sigma = y ~ btree(x1,x2))

model <- gamboostLSS(formula_, families = NBinomialLSS(), data = dat, control = boost_control(mstop = 400)) 
```

Any guidance would be highly appreciated.

Thanks in advance! :)

**Comment by hofnerb** [comment]
You can simply plot the model to obtain the finally fitted surfaces / interactions:
```R
plot(model)
```
or plot single effects by directly specifiying them e.g. 
```R
plot(model, paramter = mu, which = 1)
```
Does this help? Is that sufficient?

Otherwise, @thothorn might be able to provide more insight into `btree` and functions to extract information from fitted `btree` objects.

**Comment by BerriJ** [comment]
Thank you very much. I thought it would be possible to somehow plot the actual fitted tree to see the splits. This would be very convenient to identify (nonlinear) interactions.
