### ISSUE TITLE
Cannot select the true covariates for logit regression using mboost

### ISSUE THREAD

**Issue by mq20097452** [boost-R/mboost#111]
Hi Benjamin,
I am trying to use mboost to select the covariates for a logit regression. However, as shown in my attached simulation file, mboost selects only one variable X3, while the true variables that affect y are X1,X2,X3,X4. Maybe I have not used mboost the way I should.
It would be greatly appreciated if you could have a look at the simulation file to see how I can improve feature selection.

Thank you so much for your help.

Regards,
CHi
[mboost_binomial.txt](https://github.com/boost-R/mboost/files/6315700/mboost_binomial.txt)

**Comment by hofnerb** [comment]
Some comments: 
1) Your data simulation does not really simulate the outcome according to your predictors as you do not randomly draw from a binomial distribution but have a fixed cutoff. 
2) 100 iterations seem simply to few (see argument grid in ?cvrisk) especially when you change nu to such a low value as 0.01. I strongly suggest to keep the default with 0.1. Note that an mstop value at the boundary of the grid means that you most likely are not there yet.
3) I do not understand why you first fit a linear model and then refit an additive model (with splines). 
Please have a look at the documention of the package especially the tutorial vignette for further details and examples.

This is most likely how the model call should look (after fixing your simulation)
```R
glm1 <- glmboost(formula, data=data,family=Binomial(), center=TRUE,
                 control=boost_control(nu=0.1, trace=TRUE))

cvm=cvrisk(glm1, grid = 0:200)
cvm 
mstop(glm1) <- cvm
coef(glm1)
```
