### ISSUE TITLE
warning, predict.mboost() with offset 

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/mboost#20]
This is just a comment about a warning. 
The warning occurs when predicting a model with newdata, where the model is specified with an offset AND `length(offset) != 1`, then one gets
`warning("Offset not used for prediction when ", sQuote("newdata"), " is specified")`
(mboost.R, line 269)

I found the warning rather misleading, as only the combination of user-specified offset of length>1 and predict with newdata is a problem (and not the newdata in general)
`warning("User-specified offset in object is longer than 1, thus offset not used for prediction when ", sQuote("newdata"), " is specified")`
Best

**Comment by hofnerb** [comment]
That sounds like a very reasonable change. Thanks

Am 17.11.2015 um 15:39 schrieb sbrockhaus:

> This is just a comment about a warning.
> The warning occurs when predicting a model with newdata, where the model
> is specified with an offset AND |length(offset) != 1|, then one gets
> |warning("Offset not used for prediction when ", sQuote("newdata"), " is
> specified")|
> (mboost.R, line 269)
> 
> I found the warning rather misleading, as only the combination of
> user-specified offset of length>1 and predict with newdata is a problem
> (and not the newdata in general)
> |warning("User-specified offset in object is longer than 1, thus offset
> not used for prediction when ", sQuote("newdata"), " is specified")|
> Best
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hofnerb/mboost/issues/20.

## 

---

Dr. rer. nat. Benjamin Hofner

Institut für Medizininformatik, Biometrie und Epidemiologie
Friedrich-Alexander-Universität Erlangen-Nürnberg
Waldstr. 6 - 91054 Erlangen - Germany

Tel: +49-9131-85-22707
Fax: +49-9131-85-25740

Büro:
   Raum 3.036
   Universitätsstraße 22
   (Eingang linke Seite des Gebäudes; Wegweiser IMBE)

benjamin.hofner@fau.de

http://www.imbe.med.uni-erlangen.de/cms/benjamin_hofner.html
http://www.benjaminhofner.de

---
