### ISSUE TITLE
C-index family... 

### ISSUE THREAD

**Issue by mayrandy** [boost-R/mboost#53]
We should include the C-index family to fit the concordance index for survival data in mboost:

Mayr, A., Hofner, B. and Schmid, M. (2016): [Boosting the discriminatory power of sparse survival models via optimization of the concordance index and stability selection](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1149-8). BMC Bioinformatics. 17:288. DOI 10.1186/s12859-016-1149-8 

Mayr, A. and Schmid, M. (2014): [Boosting the concordance index for survival data - a unified framework to derive and evaluate biomarker combinations.](http://dx.plos.org/10.1371/journal.pone.0084483) PLoS ONE 9(1): e84483. doi:10.1371/journal.pone.0084483.

**Comment by hofnerb** [comment]
yeah, of course we should. please feel free to go ahead.
