### ISSUE TITLE
Allow mboost models with mstop=0

### ISSUE THREAD

**Issue by ja-thomas** [boost-R/mboost#64]
It might be useful in general to allow mboost models with `mstop=0`, i.e., models that have been initialized with the optimal constant prediction but without any iterations. 

For example as baseline for comparison.

Explicitly this is required to solve this issue for gamboostLSS https://github.com/boost-R/gamboostLSS/issues/22

**Comment by hofnerb** [comment]
it's harder and has more side effects than I thought but I'm on my way :)
