### ISSUE TITLE
[Feature Request] model.matrix for base-learners

### ISSUE THREAD

**Issue by carlganz** [boost-R/mboost#67]
Hello,

Thank you for the wonderful package. I am in a situation where I have used `brad` for radial smoothing, and want to see the model.matrix. I see in the code there is `X_brad` but this is not exported, and difficult to work with directly. Would it be possible to add a `model.matrix` function for base-learners?

Regards,
Carl

**Comment by carlganz** [comment]
This is what `extract` is for it seems.

**Comment by hofnerb** [comment]
correct :) perhaps we could add `model.matrix` as a wrapper for the corresponding `extract` function...

**Comment by hofnerb** [comment]
I just checked `model.matrix`. According to the manual, it 

> creates a design (or model) matrix, e.g., by expanding factors to a set of dummary variables (depending on the contrasts) and expanding interactions similarly.

Hence, using `model.matrix` as a wrapper to `extract( , what = "design")` seems not sensible as the latter does not create the model matrix but extracts it from a specific object.
