### ISSUE TITLE
predict model with mstop = 0 ignores newdata

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/mboost#74]
If a model object with mstop = 0 is used for prediction the argument newdata is ignored, i.e., for 
`predict(m[0], newdata = data)`
the argument newdata is not used. 

Consider the following MWE:

```
###########################################################
## build model from the help page 

data("bodyfat", package = "TH.data")
mod <- mboost(DEXfat ~ btree(age) + bols(waistcirc) + bbs(hipcirc),
              data = bodyfat)

###########################################################
## minor problem: the format of the output changes

## look at predictions with more than 0 iterations ...
str(predict(mod[250]))

## ... and with 0 boosting iterations
str(predict(mod[0]))

###########################################################
## major problem: with mstop = 0, newdata is ignored  

## for mstop > 0 all works fine
str(predict(mod[250], newdata = bodyfat[1:10, ]))

## for mstop = 0 it looks like newdata is ignored, 
## as still 71 instead of 10 predicted values are returned 
str(predict(mod[0], newdata = bodyfat[1:10, ]))

```

For me this is a problem as it causes errors in resampling with `FDboost::applyFolds()` when mstop = 0.

**Comment by hofnerb** [comment]
I see. `newdata` has no real impact as it is not used for prediction but it should influence the size of the offset vector. Is that correct and sufficient for your scenario?

**Comment by sbrockhaus** [comment]
Yes, that would be sufficient.

**Comment by hofnerb** [comment]
And what should happen if the offset was user-specified? Should we then return NULL and a warning? Or even better an error?

**Comment by sbrockhaus** [comment]
Good question... 

If the offset has length 1, I would rather return the user-specified offset as fitting to the size of the input offset. 
```
mod <- mboost(DEXfat ~ btree(age) + bols(waistcirc) + bbs(hipcirc),
              data = bodyfat, offset = 15)
str(predict(mod[0], newdata = bodyfat[1:10, ]))
```

If the offset has length n, it is not used for the prediciton with newdata, see 
```
mod <- mboost(DEXfat ~ btree(age) + bols(waistcirc) + bbs(hipcirc),
              data = bodyfat, offset = 1:71)
str(predict(mod[250], newdata = bodyfat[1:10, ]))
str(predict(mod[0], newdata = bodyfat[1:10, ]))
```

For me it would be easiest if predict() returns basically the same things irrespective if mstop = 0 or mstop >0.

**Comment by sbrockhaus** [comment]
Would it make sense to return a vector of zeros in the case of an offset of length n? 
The reasoning would be that this is what happens to the offset in case of predict() with mstop >0

**Comment by hofnerb** [comment]
For the time being I'll issue a warning. And yes, we can return zeros. Not a bad idea. I'll do that,

**Comment by sbrockhaus** [comment]
a warning is definitely a good idea! Thanks :-)

**Comment by hofnerb** [comment]
Thanks, Sarah. You were just right in time :)

**Comment by sbrockhaus** [comment]
Good luck for me ;-)
