### ISSUE TITLE
fitted.mboost() breaks when called with argument newdata

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/mboost#76]
I am not sure whether this behaviour is on purpose or not. Anyway, `fitted.mboost()` breaks when called with the argument `newdata`. 

```r
library(mboost)
data("bodyfat", package = "TH.data")
mod <- mboost(DEXfat ~ btree(age) + bols(waistcirc) + bbs(hipcirc),
                data = bodyfat)

fitted(mod, newdata = bodyfat)
```
yields 

```
Error in predict.mboost(object, newdata = NULL, ...) : 
  formal argument "newdata" matched by multiple actual arguments
```

It would be very easy to fix `fitted.mboost()` such that it behaves just as `predict.mboost()` when called with `newdata` by deleting `newdata=NULL` in https://github.com/boost-R/mboost/blob/master/R/methods.R#L211:

```r
### compute fitted values
fitted.mboost <- function(object, ...) {
  args <- list(...)
  if (length(args) == 0) {
    ret <- object$fitted()
    if (length(ret) == length(object$rownames))
      names(ret) <- object$rownames
  } else {
    ret <- predict(object, ...)
    #if (NROW(ret) == length(ret))
    #    rownames(ret) <- object$rownames
  }
  ret
}
```

The question is, do we want this behaviour? Or generally ignore `newdata` in `fitted()`? Or throw a warning / error?

**Comment by hofnerb** [comment]
I see that it would be easy to fix the issue but I would hesitate to do that as fitted() should extract fitted values and not make predictions. That is what predict is for. Hence, I think we should discard `newdata` and issue a warning that this has happened. Can you provide a fix or shall I go ahead?

**Comment by hofnerb** [comment]
Btw. I am planning to submit mboost today (given Torstens patch works) and we should hence submit gamboostLSS tomorrow (and then FDboost).

**Comment by sbrockhaus** [comment]
To be honest, I would be happy if you could provide a fix for newdata. I am just into testing... 
Thanks for the update. I will finish testing tonight :-)

**Comment by hofnerb** [comment]
Fine. I am on my way :)

**Comment by sbrockhaus** [comment]
Thanks a lot!
