### ISSUE TITLE
improve help for bkernel()

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/mboost#78]
The new base-learner `bkernel()` shows up on the help page with the other base-learners but does not have explications in Details. And there is no reference to Friedrichs et. al (2017).

**Comment by hofnerb** [comment]
Darn! You are slightly to late ;)
We'll have ro fix this with the next release. Thx for pointing this out.

**Comment by hofnerb** [comment]
Fixed in commit f6b088422
