### ISSUE TITLE
%X% with base-learners that have design matrices with different row numbers

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/mboost#79]
When two base-learners are connected by `%X%` and one of them has shorter data, the design matrix is simply repeated. See 

```r
library(mboost)

mydat <- list(x_10 = 1:10, x_20 = 1:20, y = rnorm(20))

## works without throwing an error / warning, ... 
m1 <- mboost(y ~ bols(x_10) %X% bols(x_20), data = mydat)

## ... as x_10 is simply repeated 
extract(m1)

## see get("%X%")
```

I was surprised that this does not throw an error or a warning. 

This is due to 
 `mf <- cbind(model.frame(bl1), model.frame(bl2))`
in 
https://github.com/boost-R/mboost/blob/master/R/bl.R#L1043

I would suggest to throw a warning, something like 

```r
if (nrow(model.frame(bl1)) != nrow(model.frame(bl2))) 
  warning("The design matrices of the two marginal base-learners imply a different number of rows: ", 
                   nrow(model.frame(bl1)), ", ", nrow(model.frame(bl2)))

```

But maybe this behavior is intended? 

@davidruegamer do you use `%X%` with differing row numbers?

**Comment by sbrockhaus** [comment]
btw. `bols(x, by = z)` behaves in the same way. 

```r
mydat <- list(x_10 = 1:10, x_20 = 1:20, y = rnorm(20))

## works without throwing an error / warning, ... 
m2 <- mboost(y ~ bols(x_20, by = x_10), data = mydat)

## ... as x_10 is simply repeated 
extract(m2)
```

**Comment by hofnerb** [comment]
Other base-learners and situations showed the same behavior. See `tests/testthat/test-baselearner.R` for a detailed list of cases.
