### ISSUE TITLE
Missing values and weights

### ISSUE THREAD

**Issue by carlganz** [boost-R/mboost#80]
Hello,

I find that that when `mboost` subsets to remove missing values [here](https://github.com/boost-R/mboost/blob/5d06f360b66620ffc9fe5b800e7c97247f27e0b8/R/mboost.R#L483) it fails to subset the weights so the dimensions don't line up down the road.

Example:

```{R}
library(mboost)
# generate random data
set.seed(2017-5-22)

weights <- sample(1:100, 100, replace=FALSE)
x <- rnorm(100)
y <- runif(100)

# create missing value
x[25] <- NA

myData <- data.frame(x=x, y=y)

# errors
mboost(
  y ~ bols(x), 
  data = myData,
  weights = weights,
  family = Gaussian()
  )

# works
mboost(
  y ~ bols(x), 
  data = myData,
  weights = weights[-25],
  family = Gaussian()
)

# base R modeling functions subset weights
lm(y ~ x, myData, weights = weights)

```

Kind Regards,
Carl Ganz

**Comment by hofnerb** [comment]
You are absolutely right. Thanks for the bug report. I will immediately see how we can fix that.
