### ISSUE TITLE
getting the out put of the ctree

### ISSUE THREAD

**Issue by msheranga** [boost-R/mboost#89]
I build the decision tree to get the segment for remarketing purpose in google analytics. after getting model how to get the condition as a text file 
![image](https://user-images.githubusercontent.com/37143766/37285143-0edf1b68-2624-11e8-9b63-9a9d5da3f111.png)

I need to get the condition as a text file

**Comment by hofnerb** [comment]
This seems to be a question regarding the package party and the ctree function therein (and/or a basic R question). The easiest way is to copy & paste the results from your R browser... 

Please ask r-help@r-project.org or the author of party for further help.
