### ISSUE TITLE
2.8.1 vs 2.9.0 differences

### ISSUE THREAD

**Issue by seqtools** [boost-R/mboost#92]
I created a R script which works well with 2.8.1, but not 2.9.0. In the new version I got error:

Error in cvrisk.mboost(object = boost, grid = 1:mstop(boost), folds = cv,  : 
  Leave-one-out cross-validation cannot be used with ‘family = CoxPH()’

When I roll back to 2.8.1, the error disappears.

Any suggestions?

**Comment by hofnerb** [comment]
Unfortunately, you are not telling us what you are doing. Are you using `family = CoxPH()` and leave-one-out crossvalidation? 

If so, that is no longer possible as the code was not working as intended. See #85 

Please reopen with more details if this does not solve your issue!
