### ISSUE TITLE
Problems with parallelization of cvrisk() when using a windows machine.

### ISSUE THREAD

**Issue by hkosm** [boost-R/mboost#93]
I'm really not understanding the connection to the parallel package here. Further documentation/examples would be highly appreciated. 
Especially from the following (and only) example i'm really having problems to understand what i'm supposed to do.

```R
#infrastructure needs to be set up in advance
cl <- makeCluster(25) # e.g. to run cvrisk on 25 nodes via PVM
myApply <- function(X, FUN, ...) {
  myFun <- function(...) {
    library("mboost") # load mboost on nodes
    FUN(...)
  }
  #further set up steps as required
  parLapply(cl = cl, X, myFun, ...)
}

cvrisk(model, papply = myApply)

stopCluster(cl)
#End(Not run)
```
Thanks in advance!

[EDIT: Code formating added for better readability]

**Comment by hofnerb** [comment]
Sorry for the very slow response. 

To be honest, I never used parallelization on a Windows machine so far. I only use the multicore functionality on Linux which works out of the box. I think you need to check examples for paralellization in your preferred package, e.g. from the core package `parallel`. 

Essentially, the only thing you need is a parallelized version of `lapply` to be fed to `papply`. On Linux this is `mclapply` (multicore apply) which works withoit any setup in advance. In the above stub from the example, this is the function `myApply` which essentially calls `parLapply` which in turn loads mboost and then evaluates the call.
